name: Build & Test
on:
  schedule:
    - cron: 0 0 * * *
  push:
  workflow_dispatch:
jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build
        run: docker build -t devcontainer .
      - name: Test
        run: bash test.sh devcontainer
